---
# Role to install open vm tools for hosts that exist inside of a virtualized environment.

- include: debian.yml
  when: ansible_distribution == 'Debian'
  tags:
    - vm-child
    - virtualization
