---
- hosts: all
  roles:
    - role: apt-install
      vars:
        packagesdep:
          - htop
          - curl
          - gnupg
          - gnupg-agent
          - ca-certificates
          - apt-transport-http
          - software-properties-common