---
# Initialize environment

- import_playbook: init.playbook.yml
- import_playbook: source-control.playbook.yml
- import_playbook: virtualization.playbook.yml
- import_playbook: cloud-cli.playbook.yml
- import_playbook: editors.playbook.yml
- import_playbook: languages.playbook.yml
