---

- name: Register VS-Code Apt Repository
  include_role:
    name: apt-register
  vars:
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    repo_os: deb
    repo_url: https://packages.microsoft.com/repos/vscode
    repo_branch: stable main
    repo_list_name: vscode

- name: Install VS-Code
  include_role:
    name: apt-install
  vars:
    package_list:
      - code
- name: Install Vetur Extension
  command: "code --install-extension octref.vetur"
- name: Install Spell Check Extension
  command: "code --install-extension streetsidesoftware.code-spell-checker"
- name: Install Docker Extension
  command: "code --install-extension ms-azuretools.vscode-docker"
- name: Install ESLint Extension
  command: "code --install-extension dbaeumer.vscode-eslint"
- name: Install ESLint Extension
  command: "code --install-extension dbaeumer.vscode-eslint"
- name: Install IntelliCode Extension
  command: "code --install-extension visualstudioexptteam.vscodeintellicode"