---

- name: Check if mongodb-compass is installed
  command: dpkg-query -W mongodb-compass
  register: mongodb_compass_check_deb
  failed_when: mongodb_compass_check_deb.rc > 1
  changed_when: mongodb_compass_check_deb.rc == 1

- name: Download mongodb-compass
  get_url: 
    url="https://downloads.mongodb.com/compass/mongodb-compass_1.33.1_amd64.deb"
    dest="/tmp/mongodb-compass_1.33.1_amd64.deb"
  when: mongodb_compass_check_deb.rc == 1

- name: Install mongodb-compass
  apt: deb="/tmp/mongodb-compass_1.33.1_amd64.deb"
  become: true
  when: mongodb_compass_check_deb.rc == 1