---

- name: Register Azure CLI Apt Repository
  include_role:
    name: apt-register
  vars:
    key_url: https://packages.microsoft.com/keys/microsoft.asc
    repo_os: deb
    repo_url: https://packages.microsoft.com/repos/azure-cli
    repo_branch: "{{ ansible_distribution_release }} main"
    repo_list_name: azure-cli

- name: Install Azure CLI
  include_role:
    name: apt-install
  vars:
    package_list:
      - azure-cli
