---

- name: Register Kubernetes Apt Repository
  include_role:
    name: apt-register
  vars:
    key_url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    repo_os: deb
    repo_url: https://apt.kubernetes.io/
    repo_branch: "kubernetes-xenial main"
    repo_list_name: kubernetes

- name: Install Kubernetes
  include_role:
    name: apt-install
  vars:
    package_list:
      - kubeadm
      - kubectl
