---

- name: Register Terraform Apt Repository
  include_role:
    name: apt-register
  vars:
    key_url: https://apt.releases.hashicorp.com/gpg
    repo_os: deb
    repo_url: https://apt.releases.hashicorp.com
    repo_branch: buster main
    repo_list_name: terraform

- name: Install Terraform
  include_role:
    name: apt-install
  vars:
    package_list:
      - terraform